---
fzf_version: "0.67.0"
fzf_binary_path: /usr/bin/fzf
fzf_archive_name: "fzf-{{ fzf_version }}-linux_amd64.tar.gz"
fzf_download_url: "https://github.com/junegunn/fzf/releases/download/v{{ fzf_version }}/{{ fzf_archive_name }}"
fzf_checksum_url: "https://github.com/junegunn/fzf/releases/download/v{{ fzf_version }}/fzf_{{ fzf_version }}_checksums.txt"
fzf_tmp_dir: "/tmp/fzf-install"

