---
- hosts: localhost
  gather_facts: true
  become: true
  vars:
    user: tb
    # dotfiles_branch: "tb/2025"
  roles:
  - fzf
  - neovim
  - helix
  - zellij
  - obsidian
  - kube-ps1
  - filen
  - proton-pass
  - opensnitch
