---
- hosts: localhost
  gather_facts: true
  become: true
  vars:
    user: tb
    dotfiles_repo: "https://github.com/tbalthazar/dotfiles"
  roles:
  - base
  - fzf
  - dotfiles
  - gnome-tweaks
  - neovim
  - helix
  - zellij
  - mise
  - languages
  - flatpak
  - firefox
  - obsidian
  - vscode
  - docker
  - kube-ps1
  - filen
  - signal
  - proton-pass
  - proton-vpn
  - opensnitch
  # - virtualbox
